<<<<<<< HEAD
theme: jekyll-theme-midnight
collections: 
  picoCTF:
    output: true
  CTFlearn:
    output: true
=======
theme: jekyll-theme-modernist
>>>>>>> 8144e42aa87be7d16b09914418826baa367dd4d8
