markdown: redcarpet
baseurl: /CTFwriteups
exclude : ['README.md','template.md']
permalink: pretty
collections: 
  CTFlearn:
    output: true
    permalink: /ctflearn/:path/
  picoCTF:
    output: true
    permalink: /picoctf/:path/
    sort_by: year
  dCTF:
    output: true
    permalink: /dctf/:path/
  shellctf:
    output: true
    permalink: /shellctf/:path/
