markdown: redcarpet
baseurl: /CTFwriteups
exclude : ['README.md']
permalink: pretty
collections: 
  helpme:
    output: true
    permalink: /helpme/:path/
  CTFlearn:
    output: true
    permalink: /ctflearn/:path/
  picoCTF:
    output: true
    permalink: /picoctf/:path/
